# Generated by Django 5.1.3 on 2024-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('analista', 'Analista')], default='admin', max_length=100),
        ),
    ]
