# Generated by Django 5.1.2 on 2024-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_full_name_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Analista', 'Analista')], default='Operador', max_length=20),
        ),
    ]
