# Generated by Django 5.1.2 on 2024-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercaderia_transportada', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('semana_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incinerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incinerado', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('semana_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mercaderia', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('semana_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_operacion', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('semana_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('semana_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semana_5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
