# Generated by Django 5.1.2 on 2024-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grua',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incinerado',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mercaderia',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operaciongeneral',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grua',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='incinerado',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mercaderia',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operaciongeneral',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
