# Generated by Django 5.1.3 on 2024-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0002_aggregateddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateddata',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aggregateddata',
            name='value',
            field=models.FloatField(),
        ),
    ]
