# Generated by Django 5.1.3 on 2024-11-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0003_alter_aggregateddata_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisosData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0.0)),
                ('period', models.CharField(max_length=50)),
            ],
        ),
    ]
