# Generated by Django 5.1.3 on 2024-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0003_historicaldata_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='region',
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='predicted_value',
            field=models.FloatField(default=0.0),
        ),
    ]
