# Generated by Django 5.1.3 on 2024-12-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0004_comisosdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grua',
            name='mercaderia_transportada',
            field=models.CharField(choices=[('MERCADERIA', 'MERCADERIA VARIADA'), ('CARBURANTES', 'CARBURANTES'), ('SUSTANCIAS_CONTROLADAS', 'SUSTANCIAS CONTROLADAS'), ('VEHICULOS', 'VEHICULOS COMISADOS E INCINERADOS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='incinerado',
            name='tipo_incinerado',
            field=models.CharField(choices=[('VEHICULOS_CHUTOS', 'INCINERACION DE VEHICULOS CHUTOS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mercaderia',
            name='tipo_mercaderia',
            field=models.CharField(choices=[('PERECEDERA', 'PERECEDERA (COMESTIBLES ENLATADOS Y AGRICOLAS)'), ('NO_PERECEDERA', 'NO PERECEDERA (LAVADORAS, MICROHONDAS, COMPUTADORAS, TELEVISORES)'), ('MERCADERIA_VARIADA', 'MERCADERIA VARIADA (PERECEDERA Y NO PERECEDERA)'), ('CARBURANTES', 'CARBURANTES'), ('SUSTANCIAS_CONTROLADAS', 'SUSTANCIAS CONTROLADAS'), ('DIVISAS', 'DIVISAS'), ('VEHICULOS', 'VEHICULOS (COMISADOS INUTILIZADOS E INCINERADOS)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='operaciongeneral',
            name='detalle_operacion',
            field=models.CharField(choices=[('PATRULLAJES MOVIL', 'PATRULLAJES MOVIL'), ('PATRULLAJES A PIE', 'PATRULLAJES A PIE'), ('PUESTOS DE CONTROL FIJO', 'PUESTOS DE CONTROL FIJO'), ('PUESTO DE CONTROL MOVILES', 'PUESTO DE CONTROL MOVILES'), ('RECONOCIMIENTO', 'RECONOCIMIENTO'), ('ESCOLTAS', 'ESCOLTAS'), ('TRASLADO DE VEHICULOS', 'TRASLADO DE VEHICULOS'), ('TRASLADO DE COMISOS O MERCADERIA', 'TRASLADO DE COMISOS O MERCADERIA'), ('OPERACIONES LOGISTICAS', 'OPERACIONES LOGISTICAS'), ('EVACUACIONES', 'EVACUACIONES'), ('ENFRENTAMIENTO CON CONTRABANDISTAS', 'ENFRENTAMIENTO CON CONTRABANDISTAS'), ('REUNION CON LOS COMUNARIOS DEL LUGAR', 'REUNION CON LOS COMUNARIOS DEL LUGAR'), ('INCINERACION DE VEHICULOS CHUTOS', 'INCINERACION DE VEHICULOS CHUTOS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('LIVIANOS', 'LIVIANOS'), ('MEDIANOS', 'MEDIANOS'), ('PESADOS', 'PESADOS'), ('MOTOCICLETAS', 'MOTOCICLETAS'), ('EMBARCACIONES', 'EMBARCACIONES')], max_length=255),
        ),
    ]
