# Generated by Django 5.1.3 on 2024-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisos', '0005_alter_grua_mercaderia_transportada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grua',
            name='mercaderia_transportada',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incinerado',
            name='tipo_incinerado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mercaderia',
            name='tipo_mercaderia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operaciongeneral',
            name='detalle_operacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=255),
        ),
    ]
